### ISSUE TITLE
false digital assignment while doing a SPI analysis

### ISSUE THREAD

**Issue by rob-mclean** [saleae/gitbook-docs#30] opened 2021-02-19 15:47 UTC
I'm using a Saleae logic pro 8, on a Windows 10 host computer, with this version of the software:

``{"Environment":"production","Branch":"master","Commit":"e566f188a06f93fafb4ef39ffcc90033ed9debb6","Version":"2.3.19","MachineID":"ed0a904b-c8ed-4ce6-bfd4-e7449c54a8b3"}``

I am trying to analyze a SPI signal, with chip-select, clock, miso, and mosi.  I am always getting a false digital conversion/assignment on the chip select signal and that is messing up the analyzer for that byte.  I've attached a screen shot of the issue.  The analog capture below shows the signal is at 0 volts when the glitch happens at 888nS from the falling edge of that signal.

The issue is very repeatable.  With the setup shown in the screen shot, the glitch happened at 888nS from the falling edge of that signal 4 out of 4 tries, and it is 4nS long.  It was sampled at 250MHz which makes it a single sample wide.

When I change the sampling rate to 500MHz, there is still a glitch that happens at 888nS, and there is also a second glitch that wasn't present at 250MHz.  The second glitch appears 998nS after the falling edge of first glitch.  Both glitches are only 2nS wide, so still 1 sample.  It is repeatable (2 out of 2 tries).

As I look at more of the transfers, I am seeing a pattern.  After a long pause where the CS signal is inactive (logic high), the first active (logic low) pulse contains one or more glitches that are 1 sample wide at one of these times from the falling edge of that first active chip select: 388nS, 640nS, or 888nS, or 988nS.  The problem persists from capture to capture.

**Workaround:**
The problem went away when I unplugged the "puck" from the computer and plugged it back in.  I left the SW running on my Windows computer when I unplugged and replugged the puck.

Given that I "fixed" the problem by power cycling to reset the puck, I'm not sure if I'm going to be able to reproduce the issue, but let me know if I can do anything more to help.

![saleae-chip-select-gitch](https://user-images.githubusercontent.com/47434689/108517913-9d4daa00-728d-11eb-9126-1d1d961bc3ca.png)

**Comment by timreyes** [comment] 2021-02-24 23:31
Sorry to hear this. The small glitch is certainly strange, but can be expected if there is some noise on the line that the analog channel is not able to catch due to different bandwidths between digital and analog paths. More info below:
https://support.saleae.com/troubleshooting/digital-and-analog-appear-different

Strangely enough, the voltage setting is set to 3.3V+, which means the threshold is sitting around 1.65V. This is already much higher than 0V, so I don't expect white noise to be the cause. One thing I notice is that the glitch is near the rising edges of other channels. My next best guess is crosstalk somewhere along the way.

One workaround is to use our glitch filter:
https://support.saleae.com/user-guide/using-logic/software-glitch-filter

In case that doesn't help, could you shoot me a message via the link below? We can continue our chat over email. Just direct the message to me (Tim) and let me know that we spoke via Github (you can provide the link to this github issue post as well).
https://contact.saleae.com/hc/en-us/requests/new

I'll go ahead and close this Github issue now in the meantime, since we reserve these github issues for support documentation issues, but looking forward to chatting with you via email in case this didn't help.

**Closed by timreyes** 2021-02-24 23:31 UTC
