### ISSUE TITLE
Channel Viewing Order

### ISSUE THREAD

**Issue by jmporter34** [saleae/gitbook-docs#11] opened 2019-06-03 17:06 UTC
Hi,
The default channel viewing order is channel 00 at the top, channel 15 at the bottom.  I want to view them in the opposite order, i.e. channel 15 at the top and channel 00 at the bottom.  It lets me drag them all around to where I want them, great.  Then I do one of any number of things (e.g. change the channel trigger spec) and it puts them all back into the default order and I have to drag them all around to where I want them again, etc.  Is there a way to lock the channel viewing order after I've customized it, so I don't have to keep doing this over and over ?  Thanks

**Comment by timreyes** [comment] 2019-06-03 22:33
Whoa! That'a a nasty bug, and is not the intended operation. I was not able to reproduce it over here.

I'd like to get a support ticket open and investigated for you. Could you email us at support@saleae.com?

Please include the following in the email:
- Request to speak to Tim and that we spoke over Github via jmporter34 (I can refer back to your Github issue).
- Your OS, and if it's 32-bit or 64-bit
- Version of Saleae Logic that you are using
- Does this occur on the latest Beta software? Download link below:
https://support.saleae.com/logic-software/latest-beta-release
- The exact steps you take to cause the issue

I'll go ahead and close this Github issue now. Let's speak over email.

**Closed by timreyes** 2019-06-03 22:33 UTC
